import 'dart:convert';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/services/claude_service.dart';
import '../../../features/profile/data/child_profile.dart';
import '../../../features/profile/view_model/profile_view_model.dart';
import '../data/content_cache.dart';
import '../data/learn_content.dart';

String _todayKey() => DateTime.now().toIso8601String().substring(0, 10);

/// Forces a new story to be generated by incrementing this counter.
/// The daily story provider watches it; incrementing invalidates the result.
final storyRefreshProvider = StateProvider<int>((_) => 0);

/// Forces a poem refresh per topic.
final poemRefreshProvider = StateProvider<int>((_) => 0);

final dailyStoryProvider = FutureProvider.autoDispose<DailyStory>((
  AutoDisposeFutureProviderRef<DailyStory> ref,
) async {
  final int refresh = ref.watch(storyRefreshProvider);
  final ClaudeService service = ref.watch(claudeServiceProvider);
  final ContentCache cache = ref.watch(contentCacheProvider);
  final ChildProfile? profile = ref.watch(profileProvider);
  final AgeBand band = profile?.ageBand ?? AgeBand.junior;
  final String key = 'story_${band.name}_${_todayKey()}_$refresh';

  final String? cached = await cache.get(key);
  if (cached != null) {
    return DailyStory.fromJson(
      jsonDecode(cached) as Map<String, dynamic>,
    );
  }

  if (!service.isConfigured) return LearnFallbacks.story;

  try {
    final DailyStory story =
        await service.generateDailyStory(band, _todayKey());
    await cache.set(key, jsonEncode(story.toJson()));
    return story;
  } catch (_) {
    return LearnFallbacks.story;
  }
});

final abcLessonProvider =
    FutureProvider.autoDispose.family<AbcLesson, String>((
  AutoDisposeFutureProviderRef<AbcLesson> ref,
  String letter,
) async {
  final ClaudeService service = ref.watch(claudeServiceProvider);
  final ContentCache cache = ref.watch(contentCacheProvider);
  final String key = 'abc_$letter';

  final String? cached = await cache.get(key);
  if (cached != null) {
    return AbcLesson.fromJson(jsonDecode(cached) as Map<String, dynamic>);
  }

  final AbcLesson? fallback = LearnFallbacks.abcLessons
      .where((AbcLesson l) => l.letter == letter)
      .firstOrNull;

  if (!service.isConfigured) {
    return fallback ?? LearnFallbacks.abcLessons.first;
  }

  try {
    final AbcLesson lesson = await service.generateAbcLesson(letter);
    await cache.set(key, jsonEncode(lesson.toJson()));
    return lesson;
  } catch (_) {
    return fallback ?? LearnFallbacks.abcLessons.first;
  }
});

final poemProvider = FutureProvider.autoDispose.family<KidsPoem, String>((
  AutoDisposeFutureProviderRef<KidsPoem> ref,
  String topic,
) async {
  final int refresh = ref.watch(poemRefreshProvider);
  final ClaudeService service = ref.watch(claudeServiceProvider);
  final ContentCache cache = ref.watch(contentCacheProvider);
  final String slug = topic.toLowerCase().replaceAll(' ', '_');
  final String key = 'poem_${slug}_$refresh';

  final String? cached = await cache.get(key);
  if (cached != null) {
    return KidsPoem.fromJson(jsonDecode(cached) as Map<String, dynamic>);
  }

  final KidsPoem? fallback = LearnFallbacks.poems
      .where((KidsPoem p) => p.topic == topic)
      .firstOrNull;

  if (!service.isConfigured) {
    return fallback ?? LearnFallbacks.poems.first;
  }

  try {
    final KidsPoem poem = await service.generatePoem(topic);
    await cache.set(key, jsonEncode(poem.toJson()));
    return poem;
  } catch (_) {
    return fallback ?? LearnFallbacks.poems.first;
  }
});
